<?php
namespace app\rbac\model;

use think\Model;

class Auth extends Model
{
    // 自动完成
    protected $autoWriteTimestamp = true;
    protected $auto = [];
    protected $insert = [];
    protected $update = [];

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    // auth 表分页查询
    public function getList()
    {
        $rs = $this
            ->field('id,name,rule,create_time,update_time,status,group_id')
            ->order('create_time desc')
            ->paginate(10);
        if($rs){
            return $rs;
        }else{
            return false;
        }
    }

    public function getAllAuth()
    {
        $rs = $this
            ->alias('a')
            ->join('sys_group b','a.group_id = b.id','left')
            ->field('a.id,a.name,a.group_id,b.name as group_name')
            ->limit(1000)
            ->select();

        $rs = collection($rs)->toArray();
        $res = [];

        foreach ($rs as $r) {
            $res[$r['group_name']][] = $r;
        }

        return $res;
    }
}
