<?php
namespace app\rbac\model;

use think\Model;

class Group extends Model
{
    // 自动完成
    protected $autoWriteTimestamp = true;
    protected $auto = [];
    protected $insert = [];
    protected $update = [];

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    // group 表分页查询
    public function getList()
    {
        $rs = $this
            ->field('id,name,create_time,update_time,status')
            ->order('create_time desc')
            ->paginate(10);
        if($rs){
            return $rs;
        }else{
            return false;
        }
    }
}