namespace app\<?=$module;?>\model;

use think\Model;

class <?=ucfirst($table_name)?> extends Model
{
    // 自动完成
    protected $autoWriteTimestamp = true;
    protected $auto = [];
    protected $insert = [];
    protected $update = [];

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    // <?=$table_name?> 表分页查询
    public function getList()
    {
        $rs = $this
            ->field('<?=$field_str?>')
            ->order('create_time desc')
            ->paginate(10);
        if($rs){
            return $rs;
        }else{
            return false;
        }
    }
}