<?php
/**
 * Created by PhpStorm.
 * User: DM
 * Date: 17/4/27
 * Time: 17:36
 */

namespace app\home\controller;


class Error extends Index
{
    public function index()
    {
        return parent::_empty(); // TODO: Change the autogenerated stub
    }
}